### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-php-cs-fixer-plugin#30]
#### Version
0.8.0

```
java.lang.NullPointerException
	at org.netbeans.modules.php.phpcsfixer.preferences.PhpCsFixerPreferences.getPreferences(PhpCsFixerPreferences.java:239)
	at org.netbeans.modules.php.phpcsfixer.preferences.PhpCsFixerPreferences.useProject(PhpCsFixerPreferences.java:90)
	at org.netbeans.modules.php.phpcsfixer.onsave.PhpCsFixerOnSaveTask.performTask(PhpCsFixerOnSaveTask.java:87)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable$1.run(BeforeSaveTasks.java:173)
	at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:356)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:156)
	at org.netbeans.modules.php.phpcsfixer.onsave.PhpCsFixerOnSaveTask.runLocked(PhpCsFixerOnSaveTask.java:108)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:153)
	at org.netbeans.modules.editor.lib.TrailingWhitespaceRemove.runLocked(TrailingWhitespaceRemove.java:102)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:153)
	at org.netbeans.modules.editor.impl.ReformatBeforeSaveTask.runLocked(ReformatBeforeSaveTask.java:124)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$TaskRunnable.run(BeforeSaveTasks.java:153)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks.runTasks(BeforeSaveTasks.java:130)
	at org.netbeans.modules.editor.lib.BeforeSaveTasks$2.run(BeforeSaveTasks.java:111)
	at org.openide.text.CloneableEditorSupport.saveDocumentImpl(CloneableEditorSupport.java:753)
	at org.openide.text.CloneableEditorSupport.saveDocument(CloneableEditorSupport.java:644)
	at org.openide.text.DataEditorSupport.superSaveDoc(DataEditorSupport.java:607)
	at org.openide.text.DataEditorSupport$SaveImpl.run(DataEditorSupport.java:1378)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:421)
	at org.openide.text.DataEditorSupport.saveDocument(DataEditorSupport.java:603)
	at org.netbeans.modules.csl.core.GsfDataObject$GenericEditorSupport$Environment$SaveSupport.save(GsfDataObject.java:224)
	at org.openide.loaders.DataObject$DOSavable.handleSave(DataObject.java:1485)
	at org.netbeans.spi.actions.AbstractSavable.save(AbstractSavable.java:107)
	at org.openide.actions.SaveAction.performAction(SaveAction.java:132)
	at org.openide.actions.SaveAction.performAction(SaveAction.java:109)
	at org.openide.actions.SaveAction$Delegate.actionPerformed(SaveAction.java:249)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:231)
	at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:260)
	at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:109)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:93)
	at org.openide.util.actions.ActionInvoker$ActionRunnable.actionPerformed(ActionInvoker.java:162)
	at org.netbeans.core.ModuleActions.invokeAction(ModuleActions.java:109)
	at org.netbeans.modules.openide.actions.ActionsBridgeImpl.invokeAction(ActionsBridgeImpl.java:60)
	at org.openide.util.actions.ActionInvoker$ActionRunnable.doRun(ActionInvoker.java:153)
	at org.openide.util.actions.ActionInvoker$2.run(ActionInvoker.java:110)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

```

**Comment by junichi11** [comment]
Fixed.
https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.8.1
